name: todo_firebase_ddd
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0
  flutter_bloc: ^6.0.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  get_it: ^4.0.4
  injectable: ^1.0.2
  flushbar: ^1.10.4

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.11.4
  injectable_generator: ^1.0.2
  lint: ^1.2.0

flutter:
  uses-material-design: true
